#pragma once
//∫Õº¸≈Ã”≥…‰Õ¨¿Ì£¨∞⁄Õ—GLFWµƒ“¿¿µ

#define GODDECAY_MOUSE_BUTTON_1         0
#define GODDECAY_MOUSE_BUTTON_2         1
#define GODDECAY_MOUSE_BUTTON_3         2
#define GODDECAY_MOUSE_BUTTON_4         3
#define GODDECAY_MOUSE_BUTTON_5         4
#define GODDECAY_MOUSE_BUTTON_6         5
#define GODDECAY_MOUSE_BUTTON_7         6
#define GODDECAY_MOUSE_BUTTON_8         7
#define GODDECAY_MOUSE_BUTTON_LAST      GLFW_MOUSE_BUTTON_8
#define GODDECAY_MOUSE_BUTTON_LEFT      GLFW_MOUSE_BUTTON_1
#define GODDECAY_MOUSE_BUTTON_RIGHT     GLFW_MOUSE_BUTTON_2
#define GODDECAY_MOUSE_BUTTON_MIDDLE    GLFW_MOUSE_BUTTON_3