#pragma once

//把GLFW头文件的宏定义扣下来变为自己引擎的按键映射，可以摆脱对GFLW的依赖

#define GODDECAY_KEY_SPACE              32
#define GODDECAY_KEY_APOSTROPHE         39 
#define GODDECAY_KEY_COMMA              44 
#define GODDECAY_KEY_MINUS              45 
#define GODDECAY_KEY_PERIOD             46 
#define GODDECAY_KEY_SLASH              47 
#define GODDECAY_KEY_0                  48
#define GODDECAY_KEY_1                  49
#define GODDECAY_KEY_2                  50
#define GODDECAY_KEY_3                  51
#define GODDECAY_KEY_4                  52
#define GODDECAY_KEY_5                  53
#define GODDECAY_KEY_6                  54
#define GODDECAY_KEY_7                  55
#define GODDECAY_KEY_8                  56
#define GODDECAY_KEY_9                  57
#define GODDECAY_KEY_SEMICOLON          59 
#define GODDECAY_KEY_EQUAL              61 
#define GODDECAY_KEY_A                  65
#define GODDECAY_KEY_B                  66
#define GODDECAY_KEY_C                  67
#define GODDECAY_KEY_D                  68
#define GODDECAY_KEY_E                  69
#define GODDECAY_KEY_F                  70
#define GODDECAY_KEY_G                  71
#define GODDECAY_KEY_H                  72
#define GODDECAY_KEY_I                  73
#define GODDECAY_KEY_J                  74
#define GODDECAY_KEY_K                  75
#define GODDECAY_KEY_L                  76
#define GODDECAY_KEY_M                  77
#define GODDECAY_KEY_N                  78
#define GODDECAY_KEY_O                  79
#define GODDECAY_KEY_P                  80
#define GODDECAY_KEY_Q                  81
#define GODDECAY_KEY_R                  82
#define GODDECAY_KEY_S                  83
#define GODDECAY_KEY_T                  84
#define GODDECAY_KEY_U                  85
#define GODDECAY_KEY_V                  86
#define GODDECAY_KEY_W                  87
#define GODDECAY_KEY_X                  88
#define GODDECAY_KEY_Y                  89
#define GODDECAY_KEY_Z                  90
#define GODDECAY_KEY_LEFT_BRACKET       91 
#define GODDECAY_KEY_BACKSLASH          92 
#define GODDECAY_KEY_RIGHT_BRACKET      93 
#define GODDECAY_KEY_GRAVE_ACCENT       96 
#define GODDECAY_KEY_WORLD_1            161
#define GODDECAY_KEY_WORLD_2            162

#define GODDECAY_KEY_ESCAPE             256
#define GODDECAY_KEY_ENTER              257
#define GODDECAY_KEY_TAB                258
#define GODDECAY_KEY_BACKSPACE          259
#define GODDECAY_KEY_INSERT             260
#define GODDECAY_KEY_DELETE             261
#define GODDECAY_KEY_RIGHT              262
#define GODDECAY_KEY_LEFT               263
#define GODDECAY_KEY_DOWN               264
#define GODDECAY_KEY_UP                 265
#define GODDECAY_KEY_PAGE_UP            266
#define GODDECAY_KEY_PAGE_DOWN          267
#define GODDECAY_KEY_HOME               268
#define GODDECAY_KEY_END                269
#define GODDECAY_KEY_CAPS_LOCK          280
#define GODDECAY_KEY_SCROLL_LOCK        281
#define GODDECAY_KEY_NUM_LOCK           282
#define GODDECAY_KEY_PRINT_SCREEN       283
#define GODDECAY_KEY_PAUSE              284
#define GODDECAY_KEY_F1                 290
#define GODDECAY_KEY_F2                 291
#define GODDECAY_KEY_F3                 292
#define GODDECAY_KEY_F4                 293
#define GODDECAY_KEY_F5                 294
#define GODDECAY_KEY_F6                 295
#define GODDECAY_KEY_F7                 296
#define GODDECAY_KEY_F8                 297
#define GODDECAY_KEY_F9                 298
#define GODDECAY_KEY_F10                299
#define GODDECAY_KEY_F11                300
#define GODDECAY_KEY_F12                301
#define GODDECAY_KEY_F13                302
#define GODDECAY_KEY_F14                303
#define GODDECAY_KEY_F15                304
#define GODDECAY_KEY_F16                305
#define GODDECAY_KEY_F17                306
#define GODDECAY_KEY_F18                307
#define GODDECAY_KEY_F19                308
#define GODDECAY_KEY_F20                309
#define GODDECAY_KEY_F21                310
#define GODDECAY_KEY_F22                311
#define GODDECAY_KEY_F23                312
#define GODDECAY_KEY_F24                313
#define GODDECAY_KEY_F25                314
#define GODDECAY_KEY_KP_0               320
#define GODDECAY_KEY_KP_1               321
#define GODDECAY_KEY_KP_2               322
#define GODDECAY_KEY_KP_3               323
#define GODDECAY_KEY_KP_4               324
#define GODDECAY_KEY_KP_5               325
#define GODDECAY_KEY_KP_6               326
#define GODDECAY_KEY_KP_7               327
#define GODDECAY_KEY_KP_8               328
#define GODDECAY_KEY_KP_9               329
#define GODDECAY_KEY_KP_DECIMAL         330
#define GODDECAY_KEY_KP_DIVIDE          331
#define GODDECAY_KEY_KP_MULTIPLY        332
#define GODDECAY_KEY_KP_SUBTRACT        333
#define GODDECAY_KEY_KP_ADD             334
#define GODDECAY_KEY_KP_ENTER           335
#define GODDECAY_KEY_KP_EQUAL           336
#define GODDECAY_KEY_LEFT_SHIFT         340
#define GODDECAY_KEY_LEFT_CONTROL       341
#define GODDECAY_KEY_LEFT_ALT           342
#define GODDECAY_KEY_LEFT_SUPER         343
#define GODDECAY_KEY_RIGHT_SHIFT        344
#define GODDECAY_KEY_RIGHT_CONTROL      345
#define GODDECAY_KEY_RIGHT_ALT          346
#define GODDECAY_KEY_RIGHT_SUPER        347
#define GODDECAY_KEY_MENU               348

//用于比较状态
#define GODDECAY_RELEASE                0
		
#define GODDECAY_PRESS                  1
		
#define GODDECAY_REPEAT					2